<section
	class="cloudflare speed auto_minify initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="auto_minify" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Auto Minify</span>
			<p>Reduce the file size of source code on your website.</p>
			<p><b>Note:</b> Purge cache to have your change take effect immediately.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" >
					<input id="javascript" value="javascript" type="checkbox" />
					<label for="javascript" >JavaScript</label>
				</div>
				<div class="group_wrapper" >
					<input id="css" value="css" type="checkbox" />
					<label for="css" >CSS</label>
				</div>
				<div class="group_wrapper" >
					<input id="html" value="html" type="checkbox" />
					<label for="html" >HTML</label>
				</div>
				<input class="trigger" data-target="change" type="button" value="Update Settings" />
			</div>
		</div>
	</div>
	<div class="row" >
		<div class="wrapper_bottom" >
			<i class="material-icons success" >done</i>
			<i class="material-icons error" >error</i>
			<i class="material-icons warning" >warning</i>
			<img class="load" src="<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>" />
			<p class="messages" ></p>
		</div>
	</div>
	<div class="lightbox" ></div>
</section>
<script>

	$j( document ).on ( "cloudflare.speed.auto_minify.initialize", function ( event, data ) {
		// var label = data.response.payload.value;
		// $j( data.section ).find ("input[name='value'][value='" + label + "']").prop ( "checked", true );
	});

	$j( document ).on ( "cloudflare.speed.auto_minify.change", function ( event, data ) {
		// var newValue = $j( data.section ).find ("input[name='value']:checked").val ();
		// setMessages ( data.section, "loading", [""] );
		// $j.ajax ({
		// 	url: data.form.endpoint,
		// 	type: "POST",
		// 	data: { "form_key": data.form.key, "value": newValue },
		// 	success: function ( response ) {
		// 		setMessages ( data.section, response.state, response.messages );
		// 	}
		// });
	});

</script>
