<section class="cloudflare speed auto_minify" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Auto Minify</span>
			<p>Reduce the file size of source code on your website.</p>
			<p><b>Note:</b> Purge cache to have your change take effect immediately.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input id="javascript" name="javascript" type="checkbox" />
				<label for="javascript" >JavaScript</label>
				<br/>
				<input id="css" name="css" type="checkbox" />
				<label for="css" >CSS</label>
				<br/>
				<input id="html" name="html" type="checkbox" />
				<label for="html" >HTML</label>
				<br/>
				<input type="button" value="Update Settings" onmouseup="submitForm ('speed-auto_minify')" />
			</div>
		</div>
	</div>
	<div class="row" >
		<div class="wrapper_bottom" >
			<i class="material-icons success" >done</i>
			<i class="material-icons error" >error_outline</i>
			<img class="load" src="<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>" />
			<p class="messages" ></p>
		</div>
	</div>
	<div class="lightbox" ></div>
</section>
