<section
	class="cloudflare speed polish initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="polish" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Polish</span>
			<p>Improve image load time by optimizing images hosted on your domain. Optionally, the WebP image codec can be used with supported clients for additional performance benefits.</p>
			<p><b>Note:</b> Purge cache to have your change take effect immediately.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" >
					<select class="selection" >
						<option value="off" >Off</option>
						<option value="lossless" >Lossless</option>
						<option value="lossy">Lossy</option>
					</select>
				</div>
				<div class="group_wrapper" >
					<input id="webp" value="webp" type="checkbox" />
					<label for="webp" >WebP</label>
				</div>
				<input class="trigger" data-target="change" type="button" value="Update Settings" />
			</div>
		</div>
	</div>
	<div class="row" >
		<div class="wrapper_bottom" >
			<i class="material-icons success" >done</i>
			<i class="material-icons error" >error</i>
			<i class="material-icons warning" >warning</i>
			<img class="load" src="<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>" />
			<p class="messages" ></p>
		</div>
	</div>
	<div class="lightbox" ></div>
</section>
