<section
	class="cloudflare crypto edge_certificates "
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="crypto"
	data-section-name="edge_certificates" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Edge Certificates</span>
			<p>Manage and purchase SSL certificates that will be served to your web visitors.</p>
			<p>Your plan includes a shared Cloudflare Universal SSL certificate. To get a dedicated certificate with custom hostnames <a href="#ordercertificate" >place a certificate order</a>.</p>
			<p>Your plan does not allow you to upload any SSL certificates, but you may <a href="#ordercertificate" >order an auto-renewing certificate</a> or <a href="#upgradeplan" >upgrade</a> to the Business plan to enable this feature.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input class="trigger full" data-target="change" type="button" value="Order SSL Certificate" />
				<input class="trigger full" data-target="change" type="button" value="Upload Custom SSL Certificate" />
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row" >
		<table cellpadding="0" cellspacing="0" >
			<thead>
				<th>Hosts</th>
				<th>Type</th>
				<th>Certificates</th>
			</thead>
		</table>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>Certificates</h4>
			<p>Cloudflare automatically provisions SSL (TLS) certificates for websites on all plans making HTTPS easy and automatic. Provisioned certificates on paid plans are <a href="https://support.cloudflare.com/hc/en-us/articles/203041594">compatible with older browsers</a>.</p>
			<p>Domains at the Business or Enterprise level of service can <a href="https://support.cloudflare.com/hc/en-us/articles/200170466-How-do-I-upload-a-custom-SSL-certificate-Business-or-Enterprise-only">upload custom certificates</a> for more advanced configurations. During upload of a custom certificate, the regions where the private key can be locally held may be specified using the ‘Private Key Restriction’ option. For optimal TLS performance, the default (distribution to all data centers) should be selected. HTTPS requests to any regions not permitted will use Keyless SSL technology to complete the handshake with the nearest allowed region.</p>
			<p>Multiple custom certificates with the same hostnames but different signature algorithms can be <a href="https://support.cloudflare.com/hc/en-us/articles/216532638">uploaded to form a certificate pack</a> to provide compatibility for older browsers. Enterprise customers can request the ability to upload multiple custom packs from their account managers.</p>
			<h4>Terms</h4>
			<p><strong>Keyless SSL:</strong> Keyless SSL is a Cloudflare-proprietary technology that allows customers to retain their SSL keys on-premise, never sharing custody of those private keys. To configure Keyless SSL, Enterprise customers should contact their account manager. Customers interested in upgrading for Keyless SSL should contact our <a href="https://www.cloudflare.com/enterprise-service-request">Enterprise sales team</a>.</p>
			<p><strong>Hosts:</strong> Hosts is the set of hostnames covered by the certificates in the certificate pack. For custom and Keyless certificate packs, the set of hostnames is determined by the hostnames present in the common name (CN) and subject alternative name (SAN) fields on the first certificate added to the pack.</p>
			<p><strong>Type:</strong> The type of a certificate pack indicates whether the pack contains Cloudflare-issued certificates, user-uploaded custom certificates, or Keyless SSL certificates.</p>
			<p><strong>Certificates:</strong> This column indicates how many certificates have been added to the pack. Mouse-over the info icon to reveal which certificates have been uploaded and when these certificates expire.</p>
		</div>
	</div>
</section>
