<section
	class="cloudflare crypto require_modern_tls initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="crypto"
	data-section-name="require_modern_tls" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Require Modern TLS</span>
			<p>Only use modern versions—1.2 and 1.3 (if enabled)—of the TLS protocol. These versions use more secure ciphers, but may restrict traffic to your site from older browsers.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is Modern TLS?</h4>
			<p>Modern TLS includes versions 1.2 and 1.3 of TLS. TLS 1.3 is the newest, fastest, and most secure version of the TLS protocol. TLS 1.2 is the version that immediately preceded 1.3 and is also considered secure. TLS is the protocol that encrypts communication between users and your website. When web traffic is encrypted with TLS, users will see the green padlock in their browser window. TLS 1.2 and 1.3 support the latest secure cryptographic ciphers that are not available in TLS version 1.0 and 1.1.</p>
			<h4>What does Require Modern TLS do?</h4>
			<p>By turning on the Require Modern TLS feature, traffic to and from your website will only be served over the TLS 1.2 or TLS 1.3 protocol. Connections from browsers that only support TLS 1.1 or earlier will be refused.</p>
			<h4>Which browsers support Modern TLS?</h4>
			<p>Modern TLS is supported by Firefox 28+, Chrome 33+, Opera 19+, Safari 7+, iOS Safari 5.1+, Android Browser 51+ and Internet Explorer 11 support TLS 1.2. Older versions of Internet Explorer (10 and earlier) do not support TLS 1.2 without a user manually enabling it.</p>
		</div>
	</div>
</section>
