<section
	class="cloudflare caching development_mode initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="caching_level" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Caching Level</span>
			<p>Determine how much of your website’s static content you want Cloudflare to cache. Increased caching can speed up page load time.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" style="max-width:160px;" >
					<input class="trigger-radio" data-target="change" id="basic" type="radio" name="value" value="basic" />
					<label for="basic" >No Query String</label>
				</div>
				<div class="group_wrapper" style="max-width:160px;" >
					<input class="trigger-radio" data-target="change" id="simplified" type="radio" name="value" value="simplified" />
					<label for="simplified" >Ignore Query String</label>
				</div>
				<div class="group_wrapper" style="max-width:160px;" >
					<input class="trigger-radio" data-target="change" id="aggressive" type="radio" name="value" value="aggressive" />
					<label for="aggressive" >Standard</label>
				</div>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>)" > </div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What are Cloudflare’s <a href="https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-Cloudflare-s-caching-levels">Caching Levels</a>?</h4>
			<p>You can set Cloudflare’s CDN to cache <a href="https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-Cloudflare-cache-for-static-content" >static content</a> according to these levels:</p>
			<ul>
				<li><strong>No Query String:</strong> Only delivers files from cache when there is no query string.</li>
				<li><strong>Ignore Query String:</strong> Delivers the same resource to everyone independent of the query string.</li>
				<li><strong>Standard:</strong> Delivers a different resource each time the query string changes.</li>
			</ul>
			<p>We recommend using the Standard level. For more detail read our KB article <a href="https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-Cloudflare-s-caching-levels" >What are Cloudflare’s Caching Levels?</a></p>
			<p><strong>Note:</strong> By default, Cloudflare does not cache HTML content. You can create a Page Rule to <a href="https://support.cloudflare.com/hc/en-us/articles/200172256-How-do-I-cache-static-HTML" >cache static HTML content</a>.</p>
			<br>
			<h5>Additional Resources</h5>
			<a href="https://support.cloudflare.com/hc/en-us/articles/200168256-What-are-Cloudflare-s-caching-levels-">What are Cloudflare's caching levels?</a>
		</div>
	</div>
</section>
