<section
	class="cloudflare caching development_mode initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="development_mode" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Development Mode</span>
			<p>Temporarily bypass our cache allowing you to see changes to your origin server in realtime.</p>
			<p><b>Note:</b> Enabling this feature can significantly increase origin server load. Development mode does not purge the cache so files will need to be purged after development mode expires.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input id="state" type="checkbox" name="mode" data-state="false" >
					<span class="slider trigger" data-target="toggle" ></span>
				</label>
			</div>
		</div>
	</div>
	<div class="row" >
		<div class="wrapper_bottom" >
			<i class="material-icons success" >done</i>
			<i class="material-icons error" >error</i>
			<i class="material-icons warning" >warning</i>
			<img class="load" src="<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>" />
			<p class="messages" ></p>
		</div>
	</div>
	<div class="lightbox" ></div>
</section>
<script>

	// $j( document ).on ( "cloudflare.caching.development_mode.initialize", function ( event, data ) {
	// 	var value = data.response.payload.value == "on" ? "true" : "false";
	// 	$j( data.section ).find ("#state").eq ( 0 ).data ( "state", value );
	// 	$j( data.section ).find ("#state").eq ( 0 ).attr ( "data-state", value );
	// });
	//
	// $j( document ).on ( "cloudflare.caching.development_mode.toggle", function ( event, data ) {
	// 	var state = $j( data.section ).find ("#state").eq ( 0 ).data ("state") == "true";
	// 	$j( data.section ).find ("#state").eq ( 0 ).data ( "state", !state + "" );
	// 	$j( data.section ).find ("#state").eq ( 0 ).attr ( "data-state", !state + "" );
	// 	setMessages ( data.section, "loading", [""] );
	// 	$j.ajax ({
	// 		url: data.form.endpoint,
	// 		type: "POST",
	// 		data: { "form_key": data.form.key, "state": !state },
	// 		success: function ( response ) {
	// 			setMessages ( data.section, response.state, response.messages );
	// 		}
	// 	});
	// });

</script>
