<section
	class="cloudflare caching purge_cache"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="purge_cache" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Purge Cache</span>
			<p>Clear cached files to force Cloudflare to fetch a fresh version of those files from your web server. You can purge files selectively or all at once.</p>
			<p><b>Note:</b> Purging the cache may temporarily degrade performance for your website.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<textarea id="files" placeholder="Separate with commas, or list one per line" ></textarea>
				<input class="trigger" data-target="individual" type="button" value="Purge Individual Files" />
				<input class="trigger" data-target="everything" type="button" value="Purge Everything" />
			</div>
		</div>
	</div>
	<div class="row" >
		<div class="wrapper_bottom" >
			<i class="material-icons success" >done</i>
			<i class="material-icons error" >error</i>
			<i class="material-icons warning" >warning</i>
			<img class="load" src="<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>" />
			<p class="messages" ></p>
		</div>
	</div>
	<div class="lightbox" ></div>
</section>
<script>

	$j( document ).on ( "cloudflare.caching.purge_cache.individual", function ( event, data ) {
		var files = $j( data.section ).find ("#files").eq ( 0 ).val ()
			.split (/\n|,/)
			.map ( i => i.trim () )
			.filter ( i => i !== "" );
		setMessages ( data.section, "loading", [""] );
		$j.ajax ({
			url: data.form.endpoint,
			type: "POST",
			data: { "form_key": data.form.key, "files": files },
			success: function ( response ) {
				setMessages ( data.section, response.state, response.messages );
			}
		});
	});

	$j( document ).on ( "cloudflare.caching.purge_cache.everything", function ( event, data ) {
		setMessages ( data.section, "loading", [""] );
		$j.ajax ({
			url: data.form.endpoint,
			type: "POST",
			data: { "form_key": data.form.key },
			success: function ( response ) {
				setMessages ( data.section, response.state, response.messages );
			}
		});
	});

</script>
