<section
	class="cloudflare dns dns_records initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="dns"
	data-section-name="dns_records" >
	<div class="row" >
		<div class="wrapper_left holds_table" >
			<span class="section_title" >DNS Records</span>
			<p>A, AAAA, and CNAME records can have their traffic routed through the Cloudflare system. Add more records using this form, and click the cloud next to each record to toggle Cloudflare on or off.</p>
			<input class="search" type="text" placeholder="Search DNS records" />
			<input class="trigger" data-target="search" type="button" value="Search" >
			<div class="group_wrapper" />
				<input type="text" placeholder="Name" />
				<input type="text" placeholder="IPv4 address" />
			</div>
			<table cellpadding="0" cellspacing="0" data-image-base="<?php echo $this->getSkinUrl ('images/cloudflare') ?>" >
				<tr>
					<th>Type</th>
					<th>Name</th>
					<th>Value</th>
					<th>TTL</th>
					<th>Status</th>
					<th></th>
				</tr>
				<tr>
					<td colspan="6" >No DNS records found.</td>
				</tr>
			</table>
		</div>
		<div class="lightbox" style="background-image: url(<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>)" > </div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is DNS?</h4>
			<p>DNS is the system at the core of the Internet that translates human-readable domain names (e.g., www.example.com) into computer-understood IP addresses (e.g., 74.125.19.99).</p>
			<p>On your Cloudflare DNS page, each DNS record will have one of these icons:</p>
			<ul>
				<li><img class='inline-image' src="<?php echo $this->getSkinUrl ('images/cloudflare/proxied_on.png') ?>" /><strong>Orange Cloud:</strong> Records that display an orange cloud icon are accelerated and protected by Cloudflare</li>
				<li><img class='inline-image' src="<?php echo $this->getSkinUrl ('images/cloudflare/proxied_off.png') ?>" /><strong>Grey Cloud:</strong> Records that display a grey cloud icon will bypass Cloudflare, using only Cloudflare DNS</li>
				<li><div class='inline-image' ></div><span class="cf-unproxied" style="background:none"></span> <strong>No Cloud:</strong> Records that do not display a cloud icon <a href="https://support.cloudflare.com/hc/en-us/articles/204643758">must bypass Cloudflare</a>, using only Cloudflare DNS.</li>
			</ul>
			<p><strong>Note:</strong> Only A, AAAA, and CNAME records with publicly routable IP addresses can have their traffic on Cloudflare.</p>
		</div>
	</div>
</section>
