<section
	class="cloudflare firewall rate_limiting initialize loading"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="rate_limiting" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Rate Limiting</span>
			<p>Protect your site or API from malicious traffic by blocking client IP addresses that hit a URL pattern and exceed a threshold you define. Your existing Rate Limiting Rules are listed below. This feature is billed on <a href="https://support.cloudflare.com/hc/en-us/articles/115000272247">usage</a>.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				Some form
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<a href="https://support.cloudflare.com/hc/en-us/articles/115001635128" >Configuring Rate Limiting from the Cloudflare Dashboard</a>
		</div>
	</div>
</section>
