<section
	class="cloudflare firewall zone_lockdown"
	data-endpoint="<?php echo $this->getApiEndpoint () ?>"
	data-form-key="<?php echo $this->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="zone_lockdown" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Zone Lockdown</span>
			<p>Lockdown a specific URL on your zone to specific IP addresses. This is useful to protect an admin or protected area from non-specified IP addresses.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				Here
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $this->getSkinUrl ('images/cloudflare/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p>Zone Lockdown allows you to whitelist specific IP addresses and IP ranges whereby all other IPs are effectively blocked. This is best used to protect an Administrative area of a website to, e.g. an office or VPN.</p>
			<p>Zone Lockdown supports:<br>Specific sub-domains, allowing you to, for example, allow IP 1.2.3.4 to access domain foo.example.com and allow IP 5.6.7.8 to access domain bar.example.com, but not necessarily allow the vice versa.<br>Specific URLs, allowing you to, for example, allow IP 1.2.3.4 to access directory example.com/foo/<em> and allow IP 5.6.7.8 to access directory example.com/bar/</em>, but not necessarily allow the vice versa.<br>This is useful when you need more granularity in your access rules since, with the IP Firewall, you can only either apply the block to all sub-domains of the current domain, or all domains on your account, and you can not specify URIs.</p>
			<p>Advanced Options:<br>In a scenario where you have multiple Zone Lockdown rules, which overlap, you can set a priority to ensure one Zone Lockdown rule is honored over another. For example, if you protected <a href="https://example.com/admin/*">https://example.com/admin/*</a> but also had <a href="https://example.com/admin/api/*">https://example.com/admin/api/*</a> - and the users to API had a different set of IP allowed IP addresses, then this would keep this area protected.</p>
		</div>
	</div>
</section>
