<h1 class="tab-content" >Speed</h1>
<h2 class="tab-content" >Manage performance settings for your website.</h2>
<?php

	echo $this->getLayout ()
		->createBlock ("cloudflare/dashboard_section_speed_autominify")
		->setTemplate ("cloudflare/speed/auto_minify.phtml")->toHtml ();

	echo $this->getLayout ()
		->createBlock ("cloudflare/dashboard_section_speed_polish")
		->setTemplate ("cloudflare/speed/polish.phtml")->toHtml ();

	echo $this->getLayout ()
		->createBlock ("cloudflare/dashboard_section_speed_rocketloader")
		->setTemplate ("cloudflare/speed/rocket_loader.phtml")->toHtml ();

?>
